apiVersion: 1
groups:
  - orgId: 1
    name: green-devops-alerts
    interval: 30s
    rules:
      - uid: p95-latency-high
        title: P95 latency > 300ms (5m)
        condition: A
        data:
          - refId: A
            relativeTimeRange: { from: 300, to: 0 }
            datasourceUid: grafana
            model:
              refId: A
              datasource: { type: prometheus, uid: Prometheus }
              expr: histogram_quantile(0.95, sum(rate(http_request_latency_seconds_bucket[5m])) by (le))
              intervalMs: 30000
              maxDataPoints: 43200
        noDataState: NoData
        execErrState: Error
        for: 2m
        annotations:
          summary: "High p95 latency over last 5m"
        labels:
          severity: warning
      - uid: error-rate-high
        title: Error rate > 1% (5m)
        condition: B
        data:
          - refId: B
            relativeTimeRange: { from: 300, to: 0 }
            datasourceUid: grafana
            model:
              refId: B
              datasource: { type: prometheus, uid: Prometheus }
              expr: |
                (sum(rate(http_requests_total{status=~"5.."}[5m])) /
                 sum(rate(http_requests_total[5m]))) * 100
              intervalMs: 30000
              maxDataPoints: 43200
        noDataState: NoData
        execErrState: Error
        for: 2m
        annotations:
          summary: "HTTP 5xx > 1% over last 5m"
        labels:
          severity: critical
