name: CI (FastAPI Optimized + Emissions)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  optimized:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
      API_TOKEN: devtoken
      CODECARBON_COUNTRY: MA
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps (get tracker + project)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Track install emissions by running pip again inside the tracker
      - name: Emissions — install
        run: |
          python tools/run_with_emissions.py --label install --outdir metrics-optimized -- pip install -r requirements.txt

      # Run tests (optimized) inside the tracker
      - name: Emissions — tests
        run: |
          python tools/run_with_emissions.py --label tests --outdir metrics-optimized -- pytest -q

      - name: Upload metrics artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metrics-optimized
          path: metrics-optimized/**

      - name: Build mini report & publish to Summary
        id: report
        shell: bash
        run: |
          mkdir -p reports
          INSTALL_KG=$(python - <<'PY'
            import json; d=json.load(open('metrics-optimized/summary_install.json')); print(d["emissions_kg"])
            PY
            )
                      TESTS_KG=$(python - <<'PY'
            import json; d=json.load(open('metrics-optimized/summary_tests.json')); print(d["emissions_kg"])
            PY
            )
                      TOTAL_KG=$(python - <<'PY'
            import json; a=json.load(open('metrics-optimized/summary_install.json'))["emissions_kg"]; b=json.load(open('metrics-optimized/summary_tests.json'))["emissions_kg"]; print(a+b)
            PY
            )
                      {
            echo "# Emissions (Optimized) — $(date -u +%Y-%m-%dT%H:%MZ)"
            echo
            echo "| Phase | kg CO₂e | g CO₂e |"
            echo "|-----:|--------:|-------:|"
            printf "| Install | %.8f | %.3f |\n" "$INSTALL_KG" "$(echo "$INSTALL_KG * 1000" | bc -l)"
            printf "| Tests   | %.8f | %.3f |\n" "$TESTS_KG" "$(echo "$TESTS_KG * 1000" | bc -l)"
            printf "| **Total** | **%.8f** | **%.3f** |\n" "$TOTAL_KG" "$(echo "$TOTAL_KG * 1000" | bc -l)"
          } | tee reports/green-devops_report.md >> "$GITHUB_STEP_SUMMARY"

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: green-devops-report
          path: reports/green-devops_report.md


      - name: Cache testmon DB
        uses: actions/cache@v4
        with:
          path: .testmondata
          key: ${{ runner.os }}-testmon-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-testmon-

    # Emissions — tests (with selective execution)
      - name: Emissions — tests
        run: |
          python tools/run_with_emissions.py --label tests --outdir metrics-optimized -- pytest -q --testmon

